backendtest/routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

/*
  |--------------------------------------------------------------------------
  | Frontend Routes
  |--------------------------------------------------------------------------
 */

// By default laravel is using routes from Auth::routes() created from php artisan make:auth
// Auth::routes()
//
// However in our application we need to create the routes manually
// Default login routes from Auth::routes()
Route::GET('/', 'Auth\LoginController@showLoginForm')->name('login');
Route::GET('admin/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::POST('admin/login', 'Auth\LoginController@login')->name('login');
// This prevents user from accessing logout via url
Route::GET('logout', 'Auth\LoginController@logout')->name('logout');

// No need registration for this project

// No need forgot password for this project

/*
  |--------------------------------------------------------------------------
  | Backend Routes
  |--------------------------------------------------------------------------
 */

// Admin backend routes - accessible after successful login
Route::GROUP(['middleware' => ['auth:user']], function () {

  // Logout
  Route::POST('logout', 'Auth\LoginController@logout')->name('logout');

  // Admin (handles users account)
  Route::GET('/admin', 'Backend\UserController@index')->name('admin');
  Route::GET('/admin/add', 'Backend\UserController@add')->name('admin.add');
  Route::POST('/admin/create', 'Backend\UserController@create')->name('admin.create');
  Route::GET('/admin/edit/{id}', 'Backend\UserController@edit')->name('admin.edit');
  Route::POST('/admin/update', 'Backend\UserController@update')->name('admin.update');
  Route::GET('/admin/delete', 'Backend\UserController@delete')->name('admin.delete');

  Route::name('admin.')->group(function () {
    Route::GET('/companies', 'Backend\CompanyController@index')->name('companies');
    Route::GET('/companies/add', 'Backend\CompanyController@add')->name('companies.add');
    Route::POST('/companies/create', 'Backend\CompanyController@create')->name('companies.create');
    Route::GET('/companies/edit/{id}', 'Backend\CompanyController@edit')->name('companies.edit');
    Route::POST('/companies/update', 'Backend\CompanyController@update')->name('companies.update');
    Route::GET('/companies/delete/{id}', 'Backend\CompanyController@delete')->name('companies.delete');
    Route::GET('/companies/postcode/{id}', 'Backend\CompanyController@postcode')->name('companies.postcode');
  });
});

backendtest/app/Http/Controllers/Backend/CompanyController.php
<?php

namespace App\Http\Controllers\Backend;


use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\Controller;
use App\Models\Company;
use App\Models\Postcode;
use App\Models\Prefecture;
use Config;
use DB;
use File;

class CompanyController extends Controller
{

  /**
   * Get named route
   *
   */
  private function getRoute()
  {
    return 'admin.companies';
  }

  /**
   * Validator for user
   *
   * @return \Illuminate\Http\Response
   */
  protected function validator(array $data, $type)
  {
    // Determine if password validation is required depending on the calling
    return Validator::make($data, [
      'name' => 'required',
      'email' => 'required|email',
      'postcode' => 'required',
      'prefecture' => 'required',
      'city' => 'required',
      'local' => 'required',
      'image' => 'required',
      // (update: not required, create: required)
    ]);
  }

  public function index()
  {
    return view('backend.companies.index');
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function add()
  {
    $prefecture = Prefecture::get();
    $company = new Company();
    $company->form_action = $this->getRoute() . '.create';
    $company->page_title = 'Company Add Page';
    $company->page_type = 'create';
    return view('backend.companies.form', [
      'prefecture' => $prefecture,
      'company' => $company,
    ]);
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function create(Request $request)
  {
    $newCompany = $request->all();

    // Validate input, indicate this is 'create' function
    $this->validator($newCompany, 'create')->validate();

    try {

      $file = $request->file('image');
      $fileName = $file->getClientOriginalName();
      $destinationPath = public_path() . '/uploads/files';
      $file->move($destinationPath, $fileName);
      $newCompany['image'] = $fileName;
      $prefectuireId = Prefecture::where('display_name', $newCompany['prefecture'])->first();
      $newCompany['prefecture_id'] = $prefectuireId['id'];
      $company = Company::create($newCompany);
      if ($company) {

        // we can use latest data first to get the ID before it stored for name of image but i think is so danger if more than 1 user do the task.
        $companyId = $company->id;
        $update = Company::find($companyId);
        $update->image = 'image_' . $companyId . '.' . $file->getClientOriginalExtension();
        $update->save();
        // Create is successful, back to list
        return redirect()->route($this->getRoute())->with('success', Config::get('const.SUCCESS_CREATE_MESSAGE'));
      } else {
        // Create is failed
        return redirect()->route($this->getRoute())->with('error', Config::get('const.FAILED_CREATE_MESSAGE'));
      }
    } catch (Exception $e) {
      // Create is failed
      return redirect()->route($this->getRoute())->with('error', Config::get('const.FAILED_CREATE_MESSAGE'));
    }
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
    $prefecture = Prefecture::get();
    $company = company::find($id);
    $company->form_action = $this->getRoute() . '.update';
    $company->page_title = 'Company Edit Page';
    // Add page type here to indicate that the form.blade.php is in 'edit' mode
    $company->page_type = 'edit';
    return view('backend.companies.form', [
      'company' => $company,
      'prefecture' => $prefecture
    ]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request)
  {
    $newCompany = $request->all();
    // dd($newCompany);
    try {
      $id = $request->get('id');
      $currentCompany = Company::find($id);
      if ($currentCompany) {

        if ($request->hasFile('image')) {
          $file = $request->file('image');
          $fileName = 'image_' . $id . '.' . $file->getClientOriginalExtension();

          $destinationPath = public_path() . '/uploads/files';
          $fileExist = $destinationPath . '/' . $fileName;
          if (File::exists($fileExist)) {
            File::delete($fileExist);
          }
          $file->move($destinationPath, $fileName);
          $newCompany['image'] = $fileName;
        } else {
          $newCompany['image'] = $currentCompany['image'];
        }
        $prefectuireId = Prefecture::where('display_name', $newCompany['prefecture'])->first();
        $newCompany['prefecture_id'] = $prefectuireId['id'];
        // Validate input only after getting password, because if not validator will keep complaining that password does not meet validation rules
        // Hashed password from DB will always have length of 60 characters so it will pass validation
        // Also indicate this is 'update' function
        $this->validator($newCompany, 'update')->validate();

        // Update user
        $currentCompany->update($newCompany);

        // If update is successful
        return redirect()->route($this->getRoute())->with('success', Config::get('const.SUCCESS_UPDATE_MESSAGE'));
      } else {
        // If update is failed
        return redirect()->route($this->getRoute())->with('error', Config::get('const.FAILED_UPDATE_MESSAGE'));
      }
    } catch (Exception $e) {
      // If update is failed
      return redirect()->route($this->getRoute())->with('error', Config::get('const.FAILED_UPDATE_MESSAGE'));
    }
  }

  public function delete($id)
  {
    try {
      // Get user by id
      $company = Company::find($id);
      // If to-delete user is not the one currently logged in, proceed with delete attempt

      // Delete user
      $company->delete();

      // If delete is successful
      return redirect()->route($this->getRoute())->with('success', Config::get('const.SUCCESS_DELETE_MESSAGE'));
    } catch (Exception $e) {
      // If delete is failed
      return redirect()->route($this->getRoute())->with('error', Config::get('const.FAILED_DELETE_MESSAGE'));
    }
  }


  public function postcode($id)
  {
    $postCodeData = Postcode::where('postcode', $id)->first();

    return response()->json($postCodeData);
  }
}

backendtest/app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\Controller;
use App\Models\User;
use Config;

class UserController extends Controller {

    /**
     * Get named route
     *
     */
    private function getRoute() {
        return 'admin';
    }

    /**
     * Validator for user
     *
     * @return \Illuminate\Http\Response
     */
    protected function validator(array $data, $type) {
        // Determine if password validation is required depending on the calling
        return Validator::make($data, [
                'username' => 'required|string|max:255|unique:users,username,' . $data['id'],
                'display_name' => 'required|string|max:100',
                // (update: not required, create: required)
                'password' => 'string|min:6|max:255',
        ]);
    }

    public function index() {
        return view('backend.users.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function add()
    {
        $user = new User();
        $user->form_action = $this->getRoute() . '.create';
        $user->page_title = 'User Add Page';
        $user->page_type = 'create';
        return view('backend.users.form', [
            'user' => $user
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request) {
        $newUser = $request->all();

        // Validate input, indicate this is 'create' function
        $this->validator($newUser, 'create')->validate();

        try {
            $newUser['password'] = bcrypt($newUser['password']);
            $user = User::create($newUser);
            if ($user) {
                // Create is successful, back to list
                return redirect()->route($this->getRoute())->with('success', Config::get('const.SUCCESS_CREATE_MESSAGE'));
            } else {
                // Create is failed
                return redirect()->route($this->getRoute())->with('error', Config::get('const.FAILED_CREATE_MESSAGE'));
            }
        } catch (Exception $e) {
            // Create is failed
            return redirect()->route($this->getRoute())->with('error', Config::get('const.FAILED_CREATE_MESSAGE'));
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $user = User::find($id);
        $user->form_action = $this->getRoute() . '.update';
        $user->page_title = 'User Edit Page';
        // Add page type here to indicate that the form.blade.php is in 'edit' mode
        $user->page_type = 'edit';
        return view('backend.users.form', [
            'user' => $user
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request) {
        $newUser = $request->all();
        try {
            $currentUser = User::find($request->get('id'));
            if ($currentUser) {
                // If password input is empty this means we take the old password value as is from DB
                if (!$newUser['password']) {
                    $newUser['password'] = $currentUser['password'];
                }
                // Validate input only after getting password, because if not validator will keep complaining that password does not meet validation rules
                // Hashed password from DB will always have length of 60 characters so it will pass validation
                // Also indicate this is 'update' function
                $this->validator($newUser, 'update')->validate();

                // Only hash the password if it needs to be hashed
                if (Hash::needsRehash($newUser['password'])) {
                    $newUser['password'] = bcrypt($newUser['password']);
                }

                // Update user
                $currentUser->update($newUser);
                // If update is successful
                return redirect()->route($this->getRoute())->with('success', Config::get('const.SUCCESS_UPDATE_MESSAGE'));
            } else {
                // If update is failed
                return redirect()->route($this->getRoute())->with('error', Config::get('const.FAILED_UPDATE_MESSAGE'));
            }
        } catch (Exception $e) {
            // If update is failed
            return redirect()->route($this->getRoute())->with('error', Config::get('const.FAILED_UPDATE_MESSAGE'));
        }
    }

    public function delete(Request $request) {
        try {
            // Get user by id
            $user = User::find($request->get('id'));
            // If to-delete user is not the one currently logged in, proceed with delete attempt
            if (Auth::id() != $user->id) {

                // Delete user
                $user->delete();

                // If delete is successful
                return redirect()->route($this->getRoute())->with('success', Config::get('const.SUCCESS_DELETE_MESSAGE'));
            }
            // Send error if logged in user trying to delete himself
            return redirect()->route($this->getRoute())->with('error', Config::get('const.FAILED_DELETE_SELF_MESSAGE'));
        } catch (Exception $e) {
            // If delete is failed
            return redirect()->route($this->getRoute())->with('error', Config::get('const.FAILED_DELETE_MESSAGE'));
        }
    }

}

backendtest/resources/views/backend/layout.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>@yield('title')</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.7 -->
        <link rel="stylesheet" href="{{ asset('bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="{{ asset('bower_components/font-awesome/css/font-awesome.min.css') }}">
        <!-- Ionicons -->
        <link rel="stylesheet" href="{{ asset('bower_components/Ionicons/css/ionicons.min.css') }}">
        <!-- jvectormap -->
        <link rel="stylesheet" href="{{ asset('bower_components/jvectormap/jquery-jvectormap.css') }}">
        <!-- Theme style -->
        <link rel="stylesheet" href="{{ asset('css/AdminLTE.min.css') }}">
        <!-- AdminLTE Skins. Choose a skin from the css/skins
             folder instead of downloading all of them to reduce the load. -->
        <link rel="stylesheet" href="{{ asset('css/skins/_all-skins.min.css') }}">
        <!-- validationEngine css -->
        <link rel="stylesheet" href="{{ asset('css/3rdparty/validation-engine/validationEngine.jquery.css') }}">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Google Font -->
        <link rel="stylesheet"
              href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        <!-- Favicon Link
        <link rel="icon" type="image/png" href="">
        -->
        @yield('css-scripts')
        <!-- backend css -->
        <link rel="stylesheet" href="{{ asset('css/backend/backend.css') }}">
    </head>
    <body class="hold-transition skin-blue-light sidebar-mini @yield('body-class')">
        <div class="wrapper">

            <header class="main-header">

                <!-- Logo -->
                <a href="{{ route('admin') }}" class="logo">
                    <!-- mini logo for sidebar mini 50x50 pixels -->
                    <span class="logo-mini">BR</span>
                    <!-- logo for regular state and mobile devices -->
                    <span class="logo-lg"><b>Backend Test</b></span>
                </a>

                <!-- Header Navbar: style can be found in header.less -->
                <nav class="navbar navbar-static-top">
                    <!-- Sidebar toggle button-->
                    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                        <span class="sr-only">Toggle navigation</span>
                    </a>
                    <!-- Navbar Right Menu -->
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="{{ route('logout') }}"
                                   onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                    <i class="fa fa-sign-out"></i></a>
                                <form id="logout-form" action="{{ route('logout') }}"
                                      method="POST" style="display: none;">{{ csrf_field() }}
                                </form>
                            </li>
                        </ul>
                    </div>

                </nav>
            </header>

            <!-- Left side column. contains the logo and sidebar -->
            <!-- Include sidebar navigation content depending on each user type-->
            <!-- The right way to do according to documentation is to use 'yield', however it does not work with reading multiple separate files-->
            <!-- Should this be implemented in controller instead of view?-->
            <aside class="main-sidebar">
                <!-- Main navigation sidebar -->
                <section class="sidebar">
                    <!-- Sidebar user panel -->
                    <div class="user-panel">
                        <div class="pull-left image">
                            <img src="{{ asset('img/ic_profile.png') }}" class="img-circle" alt="User Image">
                        </div>
                        <div class="pull-left info">
                            <p>{{ Auth::user()->username }}</p>
                            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                        </div>
                    </div>
                    <!-- sidebar menu: : style can be found in sidebar.less -->
                    <ul class="sidebar-menu" data-widget="tree">

                        <li class="header">MAIN NAVIGATION</li>

                        <li id="menu-users" class="treeview">
                            <a href="#">
                                <i class="fa fa-building-o"></i>
                                <span>Users</span>
                            </a>
                            <ul class="treeview-menu">
                                <li class="edit-users"><a href="{{ route('admin.add') }}"><i class="fa fa-circle-o"></i> Add / Edit</a></li>
                                <li class="list-users"><a href="{{ route('admin') }}"><i class="fa fa-circle-o"></i> List</a></li>
                            </ul>
                        </li>

                        <li id="menu-companies" class="treeview">
                            <a href="#">
                                <i class="fa fa-building-o"></i>
                                <span>Companies</span>
                            </a>
                            <ul class="treeview-menu">
                                <li class="add-companies"><a href="{{ route('admin.companies.add') }}"><i class="fa fa-circle-o"></i> Add / Edit</a></li>
                                <li class="list-companies"><a href="{{ route('admin.companies') }}"><i class="fa fa-circle-o"></i> List</a></li>
                            </ul>
                        </li>
                    </ul>
                </section>
            </aside>
            <!-- /.sidebar-wrapper -->

            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                @yield('content')
            </div>
            <!-- /.content-wrapper -->

            <footer class="main-footer">
                <div class="version hidden-xs">
                    <b>Version</b> 1.0.0
                </div>
            </footer>

        </div>
        <!-- ./wrapper -->

        <!-- jQuery 3 -->
        <script src="{{ asset('bower_components/jquery/dist/jquery.min.js') }}"></script>
        <script src="{{ asset('bower_components/jquery-cookie/jquery.cookie.min.js') }}"></script>
        <!-- Bootstrap 3.3.7 -->
        <script src="{{ asset('bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
        <!-- FastClick -->
        <script src="{{ asset('bower_components/fastclick/lib/fastclick.js') }}"></script>
        <!-- AdminLTE App -->
        <script src="{{ asset('js/adminlte.min.js') }}"></script>
        <!-- SlimScroll -->
        <script src="{{ asset('bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
        <!-- ChartJS -->
        <script src="{{ asset('bower_components/chart.js/Chart.js') }}"></script>

        <script src="{{ asset('js/backend/backend.js') }}"></script>
        <script type="text/javascript"> var rootUrl = "{{ url('/') }}";</script>
        @yield('js-scripts')
    </body>
</html>